import { StyleSheet } from 'react-native'
import { PhoneWidth, PhoneHeight } from '../../constants/config'


export default StyleSheet.create({
    container: {
        flex: 1,
    },
    subContainer: {
        flex: 1,
        width: PhoneWidth,
        backgroundColor: 'white',
    },
    headerContainer: {
        width: '100%',
        height: PhoneHeight * 0.15,
        paddingHorizontal: PhoneWidth * 0.03,
        justifyContent: 'center',
    },
    headerText: {
        fontSize: 22,
        color: 'black',
        fontWeight: '700',
    },
    allInfoContainer: {
        width: '100%',
        paddingHorizontal: PhoneWidth * 0.03,
    },
    anInfoBox: {
        width: '100%',
        height: PhoneHeight * 0.12,
    },
    infoText: {
        width: '100%',
        fontSize: 16,
        color: 'black',
        fontWeight: '700',
        marginBottom: 10,
    },
    infoInput: {
        width: '100%',
        height: PhoneHeight * 0.06,
        paddingHorizontal: PhoneWidth * 0.04,
        borderWidth: 0.5,
        borderColor: 'gray',
        borderRadius: PhoneWidth * 0.02,
        fontSize: 16,
        color: 'black',
        fontWeight: '400',
    },
    infoInputFocus: {
        width: '100%',
        height: PhoneHeight * 0.06,
        paddingHorizontal: PhoneWidth * 0.04,
        borderWidth: 2,
        borderColor: 'gray',
        borderRadius: PhoneWidth * 0.02,
        fontSize: 16,
        color: 'black',
        fontWeight: '400',
    },
    phoneBox: {
        justifyContent: 'space-around',
        width: '100%',
        height: PhoneHeight * 0.1,
        paddingHorizontal: PhoneWidth * 0.03,
        borderWidth: 0.5,
        borderColor: 'lightgray',
        backgroundColor: 'lightgray',
        fontSize: 16,
        color: 'black',
        fontWeight: '400',
    },
    phoneText: {
        fontSize: 14,
        color: 'gray',
        fontWeight: '400',
    },
    checkBoxContainer: {
        width: '100%',
        paddingTop: 20,
        marginRight: 15,
        marginBottom: 20,
    },
    checkBoxItem: {
        marginBottom: 20,
        flexDirection: 'row',
    },
    checkBoxButton: {
        borderWidth: 1,
        height: 20,
        width: 20,
        borderRadius: 5,
        marginRight: 10,
        borderColor: 'gray',
        justifyContent: 'center',
        alignItems: 'center',
    },
    checkBoxButtonChecked: {
        borderWidth: 1,
        width: 15,
        height: 15,
        borderRadius: 3.5,
        borderColor: 'black',
        backgroundColor: 'black',
    },
    checkBoxText: {
        fontSize: 14,
        color: 'black',
        fontWeight: '400',
    },
    saveButtonContainer: {
        height: PhoneHeight * 0.1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'white',
    },
    saveButton: {
        height: PhoneHeight * 0.06,
        width: PhoneWidth * 0.94,
        backgroundColor: '#a800ff',
        borderWidth: 1,
        borderColor:'#a800ff',
        borderRadius: PhoneWidth * 0.01,
        alignSelf: 'center',
        justifyContent: 'center',
        alignItems: 'center',
    },
    saveButtonText: {
        fontSize: 18,
        fontWeight: '500',
        color: 'white',
    },
    adressContainer: {
        width: '100%',
        height: PhoneHeight * 0.12,
    },
    adressBox: {
        height: PhoneHeight * 0.06,
        paddingHorizontal: PhoneWidth * 0.04,
        borderWidth: 0.5,
        borderColor: 'gray',
        borderRadius: PhoneWidth * 0.02,
        fontSize: 16,
        color: 'black',
        fontWeight: '400',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    optionTexts: {
        fontSize: 16,
        color: 'black',
        fontWeight: '400',
    },
    modalOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
        width: '60%',
        maxHeight: '40%',
        backgroundColor: 'white',
        borderRadius: 10,
        padding: 20,
    },
    options: {
        fontSize: 16,
        color: 'black',
        fontWeight: '400',
        padding: 10,
        borderBottomWidth: 0.5,
        borderBottomColor:'gray',
    }
})