import { StyleSheet } from 'react-native'
import { PhoneWidth, PhoneHeight } from '../../constants/config'

export default StyleSheet.create({
container: {
    flex: 1,
    backgroundColor: 'white',
  },
  subContainer: {
    flex: 1,
  },
  serviceImage: {
    width: '100%',
    height: PhoneHeight * 0.3,
    marginBottom: 15,
  },
  detailsContainer: {
    paddingBottom: 50,
    paddingHorizontal: PhoneWidth * 0.04,
  },
  detailsTextContainer: {
    borderWidth: 0.5,
    borderColor: 'gray',
    borderRadius: PhoneWidth * 0.015,
    elevation: 2,
    backgroundColor:'white',
    paddingHorizontal: 15,
    paddingVertical: 20,
  },
  serviceName: {
    fontSize: 22,
    fontFamily: 'PJMasks-Bold',
    color: 'black',
    borderBottomWidth: 0.5,
    borderBottomColor: 'gray',
    paddingBottom: 5,
    marginBottom: 10,
  },
  serviceWanter: {
    fontSize: 16,
    fontFamily: 'PJMasks-Regular',
    borderBottomWidth: 0.5,
    borderBottomColor: 'gray',
    color: 'gray',
    paddingBottom: 5,
    marginBottom: 10,
  },
  serviceDate: {
    fontSize: 16,
    fontFamily: 'PJMasks-Regular',
    borderBottomWidth: 0.5,
    borderBottomColor: 'gray',
    color: 'gray',
    paddingBottom: 5,
    marginBottom: 10,
  },
  phoneNumber: {
    fontSize: 16,
    fontFamily: 'PJMasks-Regular',
    borderBottomWidth: 0.5,
    borderBottomColor: 'gray',
    color: 'gray',
    paddingBottom: 5,
    marginBottom: 30,
  },
  detailsLabel: {
    fontSize: 20,
    fontFamily: 'PJMasks-Bold',
    color: 'black',
    marginBottom: 10,
  },
  detailsText: {
    fontSize: 16,
    fontFamily: 'PJMasks-Regular',
    borderBottomWidth: 0.5,
    borderBottomColor: 'gray',
    color: 'black',
    paddingBottom: 5,
    marginBottom: 10,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: 'white',
    borderTopWidth: 0.5,
    borderTopColor: 'lightgray',
  },
  acceptButton: {
    flex: 1,
    backgroundColor: '#4CAF50',
    padding: 12,
    borderRadius: PhoneWidth * 0.01,
    marginRight: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButton: {
    flex: 1,
    backgroundColor: '#a800ff',
    padding: 16,
    borderRadius: PhoneWidth * 0.01,
    marginLeft: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    fontFamily: 'Library 3 am',
    color: 'white',
    fontSize: 16,
  },
})